### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by gakuseh** [BaconErie/rocketblock#1]
# v1.0

Polishes up extension and makes it ready for release - End of June 2023

- [x] Make build process easier
- [x] Fix button animations
- [x] Add a title
- [ ] Draw a logo and let clicking on extension badge to open options
- [x] Update timer on end
- [ ] Use background scripts instead of content scripts to detect whether or not to block
- [ ] Allow blocking chrome://extensions
- [x] Update README

# v1.1

Makes the extension more effective - July 2023

- [ ] Create standalone software that can detect whether the extension is installed and will shut down Chrome if it is uninstalled
- [ ] Allow user to set a time on specific days of the week to automatically start blocking
- [ ] Emergency shutdown method
- [ ] Chrome Webstore listing????

# v1.2

The Blocklist Update - August 2023

- [ ] Allow only blocking a blocklist
- [ ] Allow connecting blocklist to a remote repo

# v1.3

December 2023

- [ ] AI that detects games
